spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: local
    password: local
    connection-timeout: 5000

queue.name: queueName
jsonQueue.name: jsonQueueName
topic.exchange: topicExchangeName
routing.key: routingKeyName
jsonRouting.key: jsonRoutingKeyName